### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by BAE2** [BSData/warpath#2]
Hi, now that Warpath v2 has been released by Mantic Games I'm creating all of the files required.  Could I be given access to replace all of the existing files please?

Also, after Warpath I'll be doing all the files for Warpath: Firefight, which is a new game released by Mantic Games.  Could I set up a new repository for this please?

**Comment by amis92** [comment]
Yeah sure. I'd ask you to first push these files into your own repo (I see you've already created an empty one). That way I can check if you know what you're doing :D

Ping me back here when it's done.

**Comment by BAE2** [comment]
Sure, but I hadn't realised you'd respond so quickly!  Only done the gst and 1/6 armies so far (part way through second) so pushed those two into my repo.  I'd appreciate it if you checked through as its the first time I've done these - if you've any comments I can build your suggestions into the other lists.

After I've finished and uploaded all the Warpath files is there any chance you could set up a new one called Warpath: Firefight that I can also contribute to please?  It's two separate games.

And after that I'll have a crack at Deadzone as I've heard it could be improved upon.

**Comment by amis92** [comment]
Haha well I do have very long response times too, so good you've done that with a time reserve.

I most probably won't have time to check thoroughly, sadly - you can ask other guys though (40k repo is busy with people, maybe someone there), but most probably just taking a look at how 40k files are built (or any other system you know) might help.

I'll give you access when you have most of the files, alright? :)

Also, no prob with creating another repo.

**Comment by BAE2** [comment]
I'm pretty confident I've got it all working right - it was just in case there were some 'don't dos' that I've missed.  I'll let you know when I'm nearly done on the last army.

**Comment by BAE2** [comment]
I'll be uploading the files tomorrow if you've had a chance to check them?  I've had a number of people user test them and they've only ever come back with minor errors (spelling, one missing constraint, one points value missed) so I'm confident about putting them up.

**Comment by BAE2** [comment]
By the way, after you've given me access and I've uploaded all the new Warpath files, could you give me access and let me sort out Deadzone before creating Warpath: Firefight please?  It's a more popular game so thought I would bring that game up to its current edition first.

**Comment by amis92** [comment]
I've dropped you an invitation to Other systems team, Deadzone is there too.

**Comment by BAE2** [comment]
Awesome.  Thanks mate!

**Comment by BAE2** [comment]
@amis92 I've released 2.0.0 on github but it's still come up with the old version and files on Appspot?
