### ISSUE TITLE
[Anon] Bug report: Forge_Fathers.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warpath#3]
**File:** Forge_Fathers.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** No

**Description:** Per the Warpath rulebook pg 112 the Hagall pattern Sturnhammer battle tank is equipped with a heavy hailstorm cannon. Per battle scribe it is equipped with a hailstorm autocannon. The 2 have very different stats.

**Comment by alpha-1983** [comment]
Indeed you're right. I've updated the entry for the tank and included it within the update I have commited minutes ago, version 2.0.3
It should be available for everyone within 12 hours.
